//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PyQSOFit_SBLg.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PyQSOFit_SBLg.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import os
        ///import warnings
        ///import numpy as np
        ///from astropy.io import fits
        ///from PyQSOFit.Components import LineDef, Section
        ///
        ///warnings.filterwarnings(&quot;ignore&quot;)
        ///
        ///# create a header
        ///hdr0 = fits.Header()
        ///hdr0[&apos;Author&apos;] = &apos;Mol the Hrafn&apos;
        ///primary_hdu = fits.PrimaryHDU(header=hdr0)
        ///
        ///# Insert here
        ///
        ///hdu1 = fits.BinTableHDU(data=newdata, header=Section.hdu_generate(), name=&apos;line_priors&apos;)
        ///conti_windows = np.rec.array([
        ///    (1150., 1170.),
        ///    (1275., 1290.),
        ///    (1350., 1360.),
        ///    (1445., 1465.),
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Component_template {
            get {
                return ResourceManager.GetString("Component_template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;line&gt;
        ///	&lt;hbbroad&gt;
        ///		&lt;lname&gt;Hb_br&lt;/lname&gt;
        ///		&lt;lcen&gt;4861.33&lt;/lcen&gt;
        ///		&lt;lscale&gt;0.005&lt;/lscale&gt;
        ///		&lt;default&gt;BEL&lt;/default&gt;		
        ///	&lt;/hbbroad&gt;
        ///
        ///	&lt;hbnarrow&gt;
        ///		&lt;lname&gt;Hb_na&lt;/lname&gt;
        ///		&lt;lcen&gt;4861.33&lt;/lcen&gt;
        ///		&lt;lscale&gt;0.002&lt;/lscale&gt;
        ///		&lt;lfwhm1&gt;50&lt;/lfwhm1&gt;
        ///		&lt;lfwhm2&gt;700&lt;/lfwhm2&gt;
        ///		&lt;lskew&gt;0&lt;/lskew&gt;
        ///		&lt;lvoff&gt;300&lt;/lvoff&gt;
        ///		&lt;vmode&gt;Free&lt;/vmode&gt;
        ///		&lt;smode&gt;Fixed&lt;/smode&gt;
        ///	&lt;/hbnarrow&gt;
        ///
        ///	&lt;oiiir&gt;
        ///		&lt;lname&gt;OIII5007c&lt;/lname&gt;
        ///		&lt;lcen&gt;5006.84&lt;/lcen&gt;
        ///		&lt;lscale&gt;0.003&lt;/lscale&gt;
        ///		&lt;defa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defLines {
            get {
                return ResourceManager.GetString("defLines", resourceCulture);
            }
        }
    }
}
